#!/usr/bin/env python
# -*- coding: utf8 -*-

"""
Even Fibonacci numbers
Problem 2

Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
"""


fibonacci = [1, 2]
next_number = 0

while next_number < 4000000:
    next_number = fibonacci[-1] + fibonacci[-2]
    fibonacci.append(next_number)

print sum(i for i in fibonacci if i % 2 == 0)


###########################################################################
#                                 Answer                                  #
###########################################################################

# 4613732
