#!/usr/bin/env python2
# -*- coding: utf8 -*-

"""
Even Fibonacci numbers
Problem 2
http://projecteuler.net/problem=2

Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
"""


def even_fibonacci(lst, limit):
    next_number = 4 * lst[-1] + lst[-2]
    if next_number < limit:
        lst.append(next_number)
        even_fibonacci(lst, limit)
    return lst

fibonacci = [2, 8]

print sum(even_fibonacci(fibonacci, 4000000))


###########################################################################
#                                 Answer                                  #
###########################################################################

# 4613732
