#!/usr/bin/env python
# -*- coding: utf8 -*-

"""
Pentagon numbers
Problem 44
http://projecteuler.net/problem=44


Pentagonal numbers are generated by the formula, Pₙ=n(3n-1)/2. The first
ten pentagonal numbers are:

        1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P₄ + P₇ = 22 + 70 = 92 = P₈. However, their difference, 70
- 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pⱼ and Pₖ, for which their sum and
difference is pentagonal and D = |Pₖ - Pⱼ| is minimised; what is the value
of D?
"""

from sys import exit

pentagon_numbers = set(i * (3 * i - 1) / 2 for i in xrange(1, 2500))

for i in sorted(pentagon_numbers):
    for j in sorted(pentagon_numbers):
        if j - i in pentagon_numbers:
            if i + j in pentagon_numbers:
                print j - i
                exit()

###########################################################################
#                                  Answer                                 #
###########################################################################

# 5482660
